### ISSUE TITLE
Did you stop building dotnet packages?

### ISSUE THREAD

**Issue by Jogai** [alucryd/aur#104]
If you dont mind me asking here. Packages like these are outdated now for a bit: https://archlinux.org/packages/community/x86_64/dotnet-sdk/ & https://archlinux.pkgs.org/rolling/extra-alucryd-x86_64/dotnet-sdk-5.0.8.sdk205-1-x86_64.pkg.tar.zst.html

**Comment by alucryd** [comment]
Yes I did, the build keeps breaking with almost every release and I still haven't found the time to fix the shiny new breakage. Looks like it doesn't like the latest lttng-ust release, but since dotnet is built using dotnet, we have a chicken and egg problem that's not easy to circumvent with our build tools so it's on hold until I find the time and will to do it.

**Comment by Jogai** [comment]
I see, no problem. In the meantime, the aur provides them too.

**Comment by Jogai** [comment]
Thats a weird coincidence. Just today I was thinking to check if dotnet 6 was in the main package repository, and I discovered you did it just today. Thanks!

**Comment by Jogai** [comment]
Sorry to bother you again, but two CVE's were fixed for dotnet 6 & 7. I think it would be good if 7.0.9 and 6.0.20 were available.

**Comment by Jogai** [comment]
For now 8 & 9 are behind because the latest are 8.0.22 & 9.0.11. Apart from that, 10 is out too. 🥺 

Reference: https://archlinux.org/packages/?sort=&q=net-&maintainer=alucryd&flagged=Flagged

Edit: as of yesterday this is resolved. (I guess it was a gift for celebrating Saint Nicholas ;))

**Comment by Jogai** [comment]
dotnet 10.0.11 has a newer sdk (10.0.400). 

If this gets annoying I'm willing to coordinate taking over packaging the dotnet packages (altough i've go no account yet on gitlab.archlinux.org).
